### PR TITLE
Fix #25 and some more

### LINKED ISSUE #25: Confusing naming for keystore type in connection properties
I think there's a confusion in some concepts which lead to incorrect naming in some connection properties.
Currently there are two properties that allow overriding the Key Manager's *provider algorithm*, not the keystore type, which is fixed to "JKS". I discovered this issue by trying to use a PKCS12 (.p12 file) keystore instead of JKS.

The Keystore Type is a different concept and possible values can be "JKS", "PKCS12", "JCEKS", "DKS", "BKS" , etc. 

```
nats.spring.key-store-type
nats.spring.trust-store-type

```
These two props default to "SunX509" which is the usual *provider algorithm* not a *keystore type*. Another well known provider algorithm is "PKIX".

In my opinion, the code in NatsConnectionProperties.java needs to be rearranged to correctly reflect these concepts and to allow using a different Keystore Type.

```
nats.spring.key-store-type=[ "JKS" | "PKCS12" | "JCEKS" | "DKS" | "BKS", "..."]
nats.spring.trust-store-type=[ "JKS" | "PKCS12" | "JCEKS" | "DKS" | "BKS", "..." ]
nats.spring.key-store-provider=["SunX509" | "PKIX"]
nats.spring.trust-store-provider=["SunX509" | "PKIX"]

```

Then the methods returning TrustManager[] and KeyManager[] should receive a string more aptly named "provider" or "providerAlgo" but not "type". 
The loadKeystore() method should be aware of a new "keyStoreType" property to instantiate KeyStore objects with the desired format.

### PR DESCRIPTION
**Pull request by dschulz**
**This changeset is about** 

1. Allow to specify KeyStore format for Key Store and Trust Store in connection properties. KeyStore format/type is now adjustable with:

```
nats.spring.key-store-type=JKS
nats.spring.trust-store-type=PKCS12
```

2. Key Store provider algorithm for these are now adjustable with:

```
nats.spring.key-store-provider=SunX509
nats.spring.trust-store-provider=PKIX
```

3. Also add support for adjusting TLS protocol version:

`nats.spring.tls-protocol=TLSv1.3`

4. Also add `spring-configuration-metadata.json` to the `META-INF` directory to assist IDEs while editing Spring Boot `application.properties` files.

Fixes https://github.com/nats-io/spring-nats/issues/25

### CODE REVIEW

File: nats-spring/src/main/java/io/nats/spring/boot/autoconfigure/NatsConnectionProperties.java [hunk 1]
```diff
@@ -656,58 +785,95 @@ protected KeyStore loadKeystore(String path, char[] password) throws IOException
...
+	 */
+	protected SSLContext createSSLContext() throws IOException, GeneralSecurityException {
+		
+		if (this.tlsProtocol == null || this.tlsProtocol.length() == 0) {
+			this.tlsProtocol = Options.DEFAULT_SSL_PROTOCOL;
+		}
+
+		SSLContext ctx = SSLContext.getInstance(this.tlsProtocol);
+		ctx.init(
+				this.createKeyManagers(this.keyStorePath, this.keyStorePassword, this.keyStoreProvider,
```
Comment (YunaBraska) [inline nats-spring/src/main/java/io/nats/spring/boot/autoconfigure/NatsConnectionProperties.java:849]: I think the formatting is broken here :/ This change makes the code harder to read.
the `this.createKeyManagers(this.keyStorePath, this.keyStorePassword` should start at the index of the the bracket from before `ctx.init(` - this would give you more space to not break the line
The closing bracket from `ctx.init(` could also have its own line as the start is having.

File: nats-spring/src/main/java/io/nats/spring/boot/autoconfigure/NatsConnectionProperties.java [hunk 2]
```diff
@@ -750,21 +913,13 @@ else if (this.username != null && this.username.length() > 0) {
...
-		" reconnectBufferSize='" + getReconnectBufferSize() + "'," +
-		" noEcho='" + getNoEcho() + "'," +
-		" utf8='" + getUtf8Support() + "'," +
-		" user='" + getUsername() + "'," +
-		" password='" + getPassword() + "'," +
-		" token='" + getToken() + "'," +
-		" creds='" + getCredentials() + "'," +
-		" nkey='" + getNkey() + "'," +
-			"}";
+		return "{" + " server='" + getServer() + "'," + " name='" + getConnectionName() + "'," + " maxReconnect='"
```
Comment (YunaBraska) [inline nats-spring/src/main/java/io/nats/spring/boot/autoconfigure/NatsConnectionProperties.java:916]: The Formation is also broken here which makes it harder to read and maintain

File: nats-spring/src/main/resources/META-INF/spring-configuration-metadata.json [hunk 3]
```diff
@@ -0,0 +1,158 @@
+{
```
Comment (YunaBraska) [inline nats-spring/src/main/resources/META-INF/spring-configuration-metadata.json:1]: Nice!

**Review by YunaBraska — APPROVED** [review]

**Comment by scottf** [comment]
@dschulz If you can check/fix the formatting as Yuna mentioned, I can merge this PR. Thanks for this contribution.

File: nats-spring/src/main/java/io/nats/spring/boot/autoconfigure/NatsConnectionProperties.java (hunk 1 above)
Comment (dschulz) [reply nats-spring/src/main/java/io/nats/spring/boot/autoconfigure/NatsConnectionProperties.java:849]: Ugh! The entire file was mangled, sorry about that. I blame my bad habit of mindlessly indenting/reformatting code all the time.
Thanks for reviewing it!

**Comment by dschulz** [comment]
Tried to restore the original formatting and rearranging the garbled sections @YunaBraska has pointed out.
